version: '3.1'
services:
    master:
        image: godatadriven/spark
        entrypoint: spark-class
        command: org.apache.spark.deploy.master.Master -h 0.0.0.0

    worker:
        image: godatadriven/spark
        entrypoint: spark-class
        command: org.apache.spark.deploy.worker.Worker spark://master:7077

    driver:
        image: godatadriven/spark
        command: --class org.apache.spark.examples.SparkPi --master spark://master:7077 /usr/spark/examples/jars/spark-examples_2.11-2.2.1.jar 1000
        ports:
          - "4040:4040"