version: '3.1'
services:
    master:
        image: godatadriven/spark:spark3
        entrypoint: spark-class
        command: org.apache.spark.deploy.master.Master -h 0.0.0.0

    worker:
        image: godatadriven/spark:spark3
        entrypoint: spark-class
        command: org.apache.spark.deploy.worker.Worker spark://master:7077

    driver:
        image: godatadriven/spark:spark3
        command: --conf spark.driver.extraJavaOptions=-Dlog4j.logLevel=DEBUG --class org.apache.spark.examples.SparkPi --master spark://master:7077 /usr/spark/examples/jars/spark-examples_2.12-3.0.0-preview.jar 1000
        ports:
          - "4040:4040"