ARG SPARK_VERSION=2.4.5

FROM godatadriven/spark:${SPARK_VERSION}

ARG HADOOP_AWS_VERSION=2.7.7
ARG AWS_JAVA_SDK_VERSION=1.7.4

# Add hadoop-aws library for S3
RUN apt-get install -y wget && \
    wget -q "https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar" && \
    mv hadoop-aws-${HADOOP_AWS_VERSION}.jar /usr/spark/jars/ && \
    wget -q "https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/${AWS_JAVA_SDK_VERSION}/aws-java-sdk-${AWS_JAVA_SDK_VERSION}.jar" && \
    mv aws-java-sdk-${AWS_JAVA_SDK_VERSION}.jar /usr/spark/jars/ && \
    apt-get remove -y wget && \
    apt-get autoremove -y && \
    apt-get clean
